// Generated by CoffeeScript 1.3.3
(function() {
  var markdownPreview;

  markdownPreview = function(previewSelector, refresh) {
    var convert, converter, preview, textarea;
    if (refresh == null) {
      refresh = 400;
    }
    textarea = this;
    preview = $(previewSelector);
    converter = new Markdown.getSanitizingConverter();
    convert = function() {
      var text;
      text = textarea.val();
      return preview.html(converter.makeHtml(text));
    };
    setInterval(convert, refresh);
    return this;
  };

  (function($) {
    return $.fn.markdownPreview = markdownPreview;
  })(jQuery);

}).call(this);
